services:
  tech_challenge_4:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  
    environment:
      - ENV=production  
    networks:
      - monitoring  

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  
    ports:
      - "9090:9090"  
    networks:
      - monitoring  
    depends_on:
      - tech_challenge_4  

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"  
    volumes:
      - grafana_data:/var/lib/grafana  
    networks:
      - monitoring  
    depends_on:
      - prometheus  

volumes:
  grafana_data:  

networks:
  monitoring:  
